package runtimeagent

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/faramesh/faramesh-core/internal/core/governance"
)

// AgentLaunchSettings controls generated agent launcher behavior (from governance.fms).
type AgentLaunchSettings struct {
	StackDir              string
	SocketPath            string
	PrimaryAgentID        string
	EnforceProfile        string // auto, full, minimal, off
	StripAmbientCreds     bool
	ProxyPort             int
	OSTier                bool
}

// SettingsFromCompiled derives launcher settings from a compiled stack.
func SettingsFromCompiled(c *governance.Compiled) AgentLaunchSettings {
	s := AgentLaunchSettings{
		StackDir:       strings.TrimSpace(c.StackDir),
		SocketPath:     c.Daemon.SocketPath,
		PrimaryAgentID: c.PrimaryAgentID,
		ProxyPort:      18443,
	}
	if c.Daemon.OSTier {
		s.OSTier = true
		s.EnforceProfile = "full"
	}
	if v := strings.TrimSpace(c.Daemon.AgentEnforceProfile); v != "" {
		s.EnforceProfile = v
	}
	if s.EnforceProfile == "" {
		s.EnforceProfile = "off"
	}
	s.StripAmbientCreds = c.Daemon.StripAmbientCredentials
	return s
}

// WriteArtifacts emits .faramesh/runtime/agent.env and .faramesh/bin/agent (no extra CLI).
func WriteArtifacts(cliPath string, settings AgentLaunchSettings) error {
	if settings.StackDir == "" {
		return fmt.Errorf("stack dir required")
	}
	runtimeDir := filepath.Join(settings.StackDir, ".faramesh", "runtime")
	binDir := filepath.Join(settings.StackDir, ".faramesh", "bin")
	if err := os.MkdirAll(runtimeDir, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return err
	}

	profile := settings.EnforceProfile
	if settings.OSTier && (profile == "" || profile == "off") {
		profile = "full"
	}

	var envLines []string
	envLines = append(envLines, fmt.Sprintf("FARAMESH_SOCKET=%s", settings.SocketPath))
	envLines = append(envLines, "FARAMESH_AUTOLOAD=1")
	if settings.PrimaryAgentID != "" {
		envLines = append(envLines, fmt.Sprintf("FARAMESH_AGENT_ID=%s", settings.PrimaryAgentID))
	}
	envLines = append(envLines, fmt.Sprintf("FARAMESH_ENFORCE_PROFILE=%s", profile))
	envLines = append(envLines, fmt.Sprintf("FARAMESH_PROXY_PORT=%d", settings.ProxyPort))
	if settings.StripAmbientCreds {
		envLines = append(envLines, "FARAMESH_STRIP_AMBIENT=1")
	}
	envPath := filepath.Join(runtimeDir, "agent.env")
	if err := os.WriteFile(envPath, []byte(strings.Join(envLines, "\n")+"\n"), 0o644); err != nil {
		return err
	}

	launcher := fmt.Sprintf(`#!/bin/sh
# Generated by faramesh apply — do not edit. Starts your agent with Faramesh env + OS sandbox.
set -e
STACK_DIR=%q
FARAMESH_CLI=%q
. "$STACK_DIR/.faramesh/runtime/agent.env"
if [ "$FARAMESH_ENFORCE_PROFILE" = "off" ] || [ "$FARAMESH_ENFORCE_PROFILE" = "minimal" ]; then
  exec "$@"
fi
exec "$FARAMESH_CLI" __agent-exec "$FARAMESH_ENFORCE_PROFILE" "$STACK_DIR" "$FARAMESH_PROXY_PORT" -- "$@"
`, settings.StackDir, cliPath)

	agentBin := filepath.Join(binDir, "agent")
	if err := os.WriteFile(agentBin, []byte(launcher), 0o755); err != nil {
		return err
	}
	_ = runtime.GOOS
	return nil
}

// LaunchHint returns the user-facing command line after apply.
func LaunchHint(stackDir string) string {
	rel := ".faramesh/bin/agent"
	if stackDir != "" {
		rel = filepath.Join(stackDir, rel)
	}
	return rel + " -- python your_agent.py"
}
