// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED Capability = 0
	Capability_CAPABILITY_SECRETS     Capability = 1
	Capability_CAPABILITY_IDENTITY    Capability = 2
	Capability_CAPABILITY_KMS         Capability = 3
	Capability_CAPABILITY_AUDIT_SINK  Capability = 4
	Capability_CAPABILITY_COST        Capability = 5
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_SECRETS",
		2: "CAPABILITY_IDENTITY",
		3: "CAPABILITY_KMS",
		4: "CAPABILITY_AUDIT_SINK",
		5: "CAPABILITY_COST",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED": 0,
		"CAPABILITY_SECRETS":     1,
		"CAPABILITY_IDENTITY":    2,
		"CAPABILITY_KMS":         3,
		"CAPABILITY_AUDIT_SINK":  4,
		"CAPABILITY_COST":        5,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_provider_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

type InitRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Config map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When true, Init validates configuration without connecting to external systems.
	DryRun        bool `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InitRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type ConfigSchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaField) Reset() {
	*x = ConfigSchemaField{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaField) ProtoMessage() {}

func (x *ConfigSchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaField.ProtoReflect.Descriptor instead.
func (*ConfigSchemaField) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigSchemaField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigSchemaField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigSchemaField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []Capability           `protobuf:"varint,1,rep,packed,name=capabilities,proto3,enum=faramesh.provider.v1.Capability" json:"capabilities,omitempty"`
	Health        *HealthStatus          `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	Schema        []*ConfigSchemaField   `protobuf:"bytes,3,rep,name=schema,proto3" json:"schema,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderInfo) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ProviderInfo) GetHealth() *HealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *ProviderInfo) GetSchema() []*ConfigSchemaField {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ProviderInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{3}
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{4}
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type SecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Opts          map[string]string      `protobuf:"bytes,2,rep,name=opts,proto3" json:"opts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRequest) Reset() {
	*x = SecretRequest{}
	mi := &file_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRequest) ProtoMessage() {}

func (x *SecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRequest.ProtoReflect.Descriptor instead.
func (*SecretRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{5}
}

func (x *SecretRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SecretRequest) GetOpts() map[string]string {
	if x != nil {
		return x.Opts
	}
	return nil
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{6}
}

func (x *Secret) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Secret) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Secret) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Svid          []byte                 `protobuf:"bytes,2,opt,name=svid,proto3" json:"svid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{7}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetSvid() []byte {
	if x != nil {
		return x.Svid
	}
	return nil
}

type VerificationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationResult) Reset() {
	*x = VerificationResult{}
	mi := &file_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResult) ProtoMessage() {}

func (x *VerificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResult.ProtoReflect.Descriptor instead.
func (*VerificationResult) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{8}
}

func (x *VerificationResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerificationResult) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *VerificationResult) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *VerificationResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	KeyRef        string                 `protobuf:"bytes,2,opt,name=key_ref,json=keyRef,proto3" json:"key_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{9}
}

func (x *SignRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignRequest) GetKeyRef() string {
	if x != nil {
		return x.KeyRef
	}
	return ""
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{10}
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Signature) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *Signature) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DPRRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanonicalJson []byte                 `protobuf:"bytes,1,opt,name=canonical_json,json=canonicalJson,proto3" json:"canonical_json,omitempty"`
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DPRRecord) Reset() {
	*x = DPRRecord{}
	mi := &file_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DPRRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPRRecord) ProtoMessage() {}

func (x *DPRRecord) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPRRecord.ProtoReflect.Descriptor instead.
func (*DPRRecord) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{11}
}

func (x *DPRRecord) GetCanonicalJson() []byte {
	if x != nil {
		return x.CanonicalJson
	}
	return nil
}

func (x *DPRRecord) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *DPRRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type SinkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinkAck) Reset() {
	*x = SinkAck{}
	mi := &file_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkAck) ProtoMessage() {}

func (x *SinkAck) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkAck.ProtoReflect.Descriptor instead.
func (*SinkAck) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{12}
}

func (x *SinkAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SinkAck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type CostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostRequest) Reset() {
	*x = CostRequest{}
	mi := &file_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostRequest) ProtoMessage() {}

func (x *CostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostRequest.ProtoReflect.Descriptor instead.
func (*CostRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{13}
}

func (x *CostRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *CostRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CostEstimateResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Amount   float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	// 0.0–1.0; providers may return 0 when unknown.
	Confidence    float64 `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostEstimateResponse) Reset() {
	*x = CostEstimateResponse{}
	mi := &file_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostEstimateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostEstimateResponse) ProtoMessage() {}

func (x *CostEstimateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostEstimateResponse.ProtoReflect.Descriptor instead.
func (*CostEstimateResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{14}
}

func (x *CostEstimateResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CostEstimateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CostEstimateResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\x12\x14faramesh.provider.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n" +
	"\vInitRequest\x12E\n" +
	"\x06config\x18\x01 \x03(\v2-.faramesh.provider.v1.InitRequest.ConfigEntryR\x06config\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x11ConfigSchemaField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xeb\x01\n" +
	"\fProviderInfo\x12D\n" +
	"\fcapabilities\x18\x01 \x03(\x0e2 .faramesh.provider.v1.CapabilityR\fcapabilities\x12:\n" +
	"\x06health\x18\x02 \x01(\v2\".faramesh.provider.v1.HealthStatusR\x06health\x12?\n" +
	"\x06schema\x18\x03 \x03(\v2'.faramesh.provider.v1.ConfigSchemaFieldR\x06schema\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\x0f\n" +
	"\rHealthRequest\"@\n" +
	"\fHealthStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x9f\x01\n" +
	"\rSecretRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12A\n" +
	"\x04opts\x18\x02 \x03(\v2-.faramesh.provider.v1.SecretRequest.OptsEntryR\x04opts\x1a7\n" +
	"\tOptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x06Secret\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12+\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\".\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04svid\x18\x02 \x01(\fR\x04svid\"\x97\x01\n" +
	"\x12VerificationResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"@\n" +
	"\vSignRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x17\n" +
	"\akey_ref\x18\x02 \x01(\tR\x06keyRef\"^\n" +
	"\tSignature\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\"j\n" +
	"\tDPRRecord\x12%\n" +
	"\x0ecanonical_json\x18\x01 \x01(\fR\rcanonicalJson\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"=\n" +
	"\aSinkAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\xc0\x01\n" +
	"\vCostRequest\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12Q\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v21.faramesh.provider.v1.CostRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x14CostEstimateResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence*\x9d\x01\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CAPABILITY_SECRETS\x10\x01\x12\x17\n" +
	"\x13CAPABILITY_IDENTITY\x10\x02\x12\x12\n" +
	"\x0eCAPABILITY_KMS\x10\x03\x12\x19\n" +
	"\x15CAPABILITY_AUDIT_SINK\x10\x04\x12\x13\n" +
	"\x0fCAPABILITY_COST\x10\x052\xda\x04\n" +
	"\x0fProviderService\x12M\n" +
	"\x04Init\x12!.faramesh.provider.v1.InitRequest\x1a\".faramesh.provider.v1.ProviderInfo\x12V\n" +
	"\vHealthCheck\x12#.faramesh.provider.v1.HealthRequest\x1a\".faramesh.provider.v1.HealthStatus\x12N\n" +
	"\tGetSecret\x12#.faramesh.provider.v1.SecretRequest\x1a\x1c.faramesh.provider.v1.Secret\x12Z\n" +
	"\x0eVerifyIdentity\x12\x1e.faramesh.provider.v1.Identity\x1a(.faramesh.provider.v1.VerificationResult\x12J\n" +
	"\x04Sign\x12!.faramesh.provider.v1.SignRequest\x1a\x1f.faramesh.provider.v1.Signature\x12I\n" +
	"\aSinkDPR\x12\x1f.faramesh.provider.v1.DPRRecord\x1a\x1d.faramesh.provider.v1.SinkAck\x12]\n" +
	"\fCostEstimate\x12!.faramesh.provider.v1.CostRequest\x1a*.faramesh.provider.v1.CostEstimateResponseB@Z>github.com/faramesh/faramesh-core/proto/provider/v1;providerv1b\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_provider_proto_goTypes = []any{
	(Capability)(0),               // 0: faramesh.provider.v1.Capability
	(*InitRequest)(nil),           // 1: faramesh.provider.v1.InitRequest
	(*ConfigSchemaField)(nil),     // 2: faramesh.provider.v1.ConfigSchemaField
	(*ProviderInfo)(nil),          // 3: faramesh.provider.v1.ProviderInfo
	(*HealthRequest)(nil),         // 4: faramesh.provider.v1.HealthRequest
	(*HealthStatus)(nil),          // 5: faramesh.provider.v1.HealthStatus
	(*SecretRequest)(nil),         // 6: faramesh.provider.v1.SecretRequest
	(*Secret)(nil),                // 7: faramesh.provider.v1.Secret
	(*Identity)(nil),              // 8: faramesh.provider.v1.Identity
	(*VerificationResult)(nil),    // 9: faramesh.provider.v1.VerificationResult
	(*SignRequest)(nil),           // 10: faramesh.provider.v1.SignRequest
	(*Signature)(nil),             // 11: faramesh.provider.v1.Signature
	(*DPRRecord)(nil),             // 12: faramesh.provider.v1.DPRRecord
	(*SinkAck)(nil),               // 13: faramesh.provider.v1.SinkAck
	(*CostRequest)(nil),           // 14: faramesh.provider.v1.CostRequest
	(*CostEstimateResponse)(nil),  // 15: faramesh.provider.v1.CostEstimateResponse
	nil,                           // 16: faramesh.provider.v1.InitRequest.ConfigEntry
	nil,                           // 17: faramesh.provider.v1.SecretRequest.OptsEntry
	nil,                           // 18: faramesh.provider.v1.CostRequest.AttributesEntry
	(*durationpb.Duration)(nil),   // 19: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_provider_proto_depIdxs = []int32{
	16, // 0: faramesh.provider.v1.InitRequest.config:type_name -> faramesh.provider.v1.InitRequest.ConfigEntry
	0,  // 1: faramesh.provider.v1.ProviderInfo.capabilities:type_name -> faramesh.provider.v1.Capability
	5,  // 2: faramesh.provider.v1.ProviderInfo.health:type_name -> faramesh.provider.v1.HealthStatus
	2,  // 3: faramesh.provider.v1.ProviderInfo.schema:type_name -> faramesh.provider.v1.ConfigSchemaField
	17, // 4: faramesh.provider.v1.SecretRequest.opts:type_name -> faramesh.provider.v1.SecretRequest.OptsEntry
	19, // 5: faramesh.provider.v1.Secret.ttl:type_name -> google.protobuf.Duration
	20, // 6: faramesh.provider.v1.VerificationResult.expires_at:type_name -> google.protobuf.Timestamp
	18, // 7: faramesh.provider.v1.CostRequest.attributes:type_name -> faramesh.provider.v1.CostRequest.AttributesEntry
	1,  // 8: faramesh.provider.v1.ProviderService.Init:input_type -> faramesh.provider.v1.InitRequest
	4,  // 9: faramesh.provider.v1.ProviderService.HealthCheck:input_type -> faramesh.provider.v1.HealthRequest
	6,  // 10: faramesh.provider.v1.ProviderService.GetSecret:input_type -> faramesh.provider.v1.SecretRequest
	8,  // 11: faramesh.provider.v1.ProviderService.VerifyIdentity:input_type -> faramesh.provider.v1.Identity
	10, // 12: faramesh.provider.v1.ProviderService.Sign:input_type -> faramesh.provider.v1.SignRequest
	12, // 13: faramesh.provider.v1.ProviderService.SinkDPR:input_type -> faramesh.provider.v1.DPRRecord
	14, // 14: faramesh.provider.v1.ProviderService.CostEstimate:input_type -> faramesh.provider.v1.CostRequest
	3,  // 15: faramesh.provider.v1.ProviderService.Init:output_type -> faramesh.provider.v1.ProviderInfo
	5,  // 16: faramesh.provider.v1.ProviderService.HealthCheck:output_type -> faramesh.provider.v1.HealthStatus
	7,  // 17: faramesh.provider.v1.ProviderService.GetSecret:output_type -> faramesh.provider.v1.Secret
	9,  // 18: faramesh.provider.v1.ProviderService.VerifyIdentity:output_type -> faramesh.provider.v1.VerificationResult
	11, // 19: faramesh.provider.v1.ProviderService.Sign:output_type -> faramesh.provider.v1.Signature
	13, // 20: faramesh.provider.v1.ProviderService.SinkDPR:output_type -> faramesh.provider.v1.SinkAck
	15, // 21: faramesh.provider.v1.ProviderService.CostEstimate:output_type -> faramesh.provider.v1.CostEstimateResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		EnumInfos:         file_provider_proto_enumTypes,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
