// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: provider.proto

package providerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderService_Init_FullMethodName           = "/faramesh.provider.v1.ProviderService/Init"
	ProviderService_HealthCheck_FullMethodName    = "/faramesh.provider.v1.ProviderService/HealthCheck"
	ProviderService_GetSecret_FullMethodName      = "/faramesh.provider.v1.ProviderService/GetSecret"
	ProviderService_VerifyIdentity_FullMethodName = "/faramesh.provider.v1.ProviderService/VerifyIdentity"
	ProviderService_Sign_FullMethodName           = "/faramesh.provider.v1.ProviderService/Sign"
	ProviderService_SinkDPR_FullMethodName        = "/faramesh.provider.v1.ProviderService/SinkDPR"
	ProviderService_CostEstimate_FullMethodName   = "/faramesh.provider.v1.ProviderService/CostEstimate"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProviderService is the only interface between the Faramesh daemon and a
// secrets backend, identity system, KMS, audit sink, or cost estimator.
// Built-in providers implement this in-process; third-party providers run as
// sidecars and listen on a Unix socket declared in the provider block source field.
type ProviderServiceClient interface {
	// Called once at startup (and during faramesh check dry-run validation).
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*ProviderInfo, error)
	// Called periodically; unhealthy providers put affected agents in deny-all mode.
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthStatus, error)
	// SECRETS capability — issue a short-lived secret for credential brokerage.
	GetSecret(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*Secret, error)
	// IDENTITY capability — verify workload identity before issuing credentials.
	VerifyIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*VerificationResult, error)
	// KMS capability — sign DPR payloads with an external key.
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*Signature, error)
	// AUDIT_SINK capability — receive a copy of each DPR as it is written.
	SinkDPR(ctx context.Context, in *DPRRecord, opts ...grpc.CallOption) (*SinkAck, error)
	// COST capability — estimate monetary cost before execution.
	CostEstimate(ctx context.Context, in *CostRequest, opts ...grpc.CallOption) (*CostEstimateResponse, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*ProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, ProviderService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, ProviderService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) GetSecret(ctx context.Context, in *SecretRequest, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, ProviderService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) VerifyIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*VerificationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificationResult)
	err := c.cc.Invoke(ctx, ProviderService_VerifyIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*Signature, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Signature)
	err := c.cc.Invoke(ctx, ProviderService_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) SinkDPR(ctx context.Context, in *DPRRecord, opts ...grpc.CallOption) (*SinkAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SinkAck)
	err := c.cc.Invoke(ctx, ProviderService_SinkDPR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CostEstimate(ctx context.Context, in *CostRequest, opts ...grpc.CallOption) (*CostEstimateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CostEstimateResponse)
	err := c.cc.Invoke(ctx, ProviderService_CostEstimate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations must embed UnimplementedProviderServiceServer
// for forward compatibility.
//
// ProviderService is the only interface between the Faramesh daemon and a
// secrets backend, identity system, KMS, audit sink, or cost estimator.
// Built-in providers implement this in-process; third-party providers run as
// sidecars and listen on a Unix socket declared in the provider block source field.
type ProviderServiceServer interface {
	// Called once at startup (and during faramesh check dry-run validation).
	Init(context.Context, *InitRequest) (*ProviderInfo, error)
	// Called periodically; unhealthy providers put affected agents in deny-all mode.
	HealthCheck(context.Context, *HealthRequest) (*HealthStatus, error)
	// SECRETS capability — issue a short-lived secret for credential brokerage.
	GetSecret(context.Context, *SecretRequest) (*Secret, error)
	// IDENTITY capability — verify workload identity before issuing credentials.
	VerifyIdentity(context.Context, *Identity) (*VerificationResult, error)
	// KMS capability — sign DPR payloads with an external key.
	Sign(context.Context, *SignRequest) (*Signature, error)
	// AUDIT_SINK capability — receive a copy of each DPR as it is written.
	SinkDPR(context.Context, *DPRRecord) (*SinkAck, error)
	// COST capability — estimate monetary cost before execution.
	CostEstimate(context.Context, *CostRequest) (*CostEstimateResponse, error)
	mustEmbedUnimplementedProviderServiceServer()
}

// UnimplementedProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) Init(context.Context, *InitRequest) (*ProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedProviderServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedProviderServiceServer) GetSecret(context.Context, *SecretRequest) (*Secret, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedProviderServiceServer) VerifyIdentity(context.Context, *Identity) (*VerificationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyIdentity not implemented")
}
func (UnimplementedProviderServiceServer) Sign(context.Context, *SignRequest) (*Signature, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedProviderServiceServer) SinkDPR(context.Context, *DPRRecord) (*SinkAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SinkDPR not implemented")
}
func (UnimplementedProviderServiceServer) CostEstimate(context.Context, *CostRequest) (*CostEstimateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CostEstimate not implemented")
}
func (UnimplementedProviderServiceServer) mustEmbedUnimplementedProviderServiceServer() {}
func (UnimplementedProviderServiceServer) testEmbeddedByValue()                         {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).GetSecret(ctx, req.(*SecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_VerifyIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).VerifyIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_VerifyIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).VerifyIdentity(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_SinkDPR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPRRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).SinkDPR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_SinkDPR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).SinkDPR(ctx, req.(*DPRRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CostEstimate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CostEstimate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_CostEstimate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CostEstimate(ctx, req.(*CostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "faramesh.provider.v1.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _ProviderService_Init_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ProviderService_HealthCheck_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _ProviderService_GetSecret_Handler,
		},
		{
			MethodName: "VerifyIdentity",
			Handler:    _ProviderService_VerifyIdentity_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _ProviderService_Sign_Handler,
		},
		{
			MethodName: "SinkDPR",
			Handler:    _ProviderService_SinkDPR_Handler,
		},
		{
			MethodName: "CostEstimate",
			Handler:    _ProviderService_CostEstimate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider.proto",
}
